/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j3_ps18851_phamvinhsang_asm.UI;

import com.microsoft.sqlserver.jdbc.SQLServerDriver;
import j3_ps18851_phamvinhsang_asm.Enity.Account;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import java.io.File;
import java.sql.*;
/**
 *
 * @author Sang
 */
public class Login extends javax.swing.JFrame implements ActionListener, Runnable {

    /**
     * Creates new form Login
     */
    String userName = "sa";
    String password = "songlong";
    String url = "jdbc:sqlserver://localhost:1433;DatabaseName=PS18851_PhamVinhSang_ASM_J3";
    ArrayList<Account> ListAcc = new ArrayList<>();
    String account_path = new File("src\\j3_ps18851_phamvinhsang_asm\\Data\\Account").getAbsolutePath();
    
    
    // cờ dùng điều chỉnh lên xuống
    boolean flag_user = true;
    // cờ dùng để nhận biết textfield
    boolean flag_password = true;
    
    boolean flag = true;

    
    
    
    public Login() {
        setUndecorated(true);
        initComponents();
        repareLogin();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage = new javax.swing.JPanel();
        lblEduSys = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelSignin = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        chkPassword = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        btnSignup = new javax.swing.JPanel();
        lblSignup = new javax.swing.JLabel();
        panelSignup = new javax.swing.JPanel();
        lblConfirm = new javax.swing.JLabel();
        lblPassword_pw = new javax.swing.JLabel();
        lblUser_su = new javax.swing.JLabel();
        lblSignUp = new javax.swing.JLabel();
        txtUser_su = new javax.swing.JTextField();
        chkShowpassword_pw = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        cboRole = new javax.swing.JComboBox<>();
        txtPassWord_su = new javax.swing.JPasswordField();
        txtConfirm_su = new javax.swing.JPasswordField();
        btnCreate = new javax.swing.JPanel();
        lblLogin1 = new javax.swing.JLabel();
        lblExit1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage.setBackground(new java.awt.Color(255, 255, 255));
        panelImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEduSys.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblEduSys.setForeground(new java.awt.Color(58, 111, 254));
        lblEduSys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/login.png"))); // NOI18N
        panelImage.add(lblEduSys, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 551));

        getContentPane().add(panelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 551));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 550));

        panelSignin.setBackground(new java.awt.Color(58, 111, 254));
        panelSignin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome!");
        panelSignin.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 300, 55));

        lblUser.setBackground(new java.awt.Color(58, 111, 254));
        lblUser.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_user_16px_1.png"))); // NOI18N
        lblUser.setText("User Name");
        panelSignin.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 100, 20));

        txtUser.setBackground(new java.awt.Color(58, 111, 254));
        txtUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });
        panelSignin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 330, 38));

        lblPassword.setBackground(new java.awt.Color(58, 111, 254));
        lblPassword.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(204, 204, 204));
        lblPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_user_16px_1.png"))); // NOI18N
        lblPassword.setText("PassWord");
        panelSignin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 90, -1));

        txtPassword.setBackground(new java.awt.Color(58, 111, 254));
        txtPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        panelSignin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 330, 40));

        chkPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkPassword.setForeground(new java.awt.Color(204, 204, 204));
        chkPassword.setText("Show Password");
        chkPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPasswordActionPerformed(evt);
            }
        });
        panelSignin.add(chkPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        btnLogin.setBackground(new java.awt.Color(249, 126, 86));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });

        lblLogin.setBackground(new java.awt.Color(102, 102, 102));
        lblLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 0, 0));
        lblLogin.setText("LOG IN");

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLoginLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSignin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 140, 40));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(204, 204, 204));
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        panelSignin.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 40, 40));

        btnSignup.setBackground(new java.awt.Color(58, 111, 254));
        btnSignup.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignupMouseExited(evt);
            }
        });

        lblSignup.setBackground(new java.awt.Color(102, 102, 102));
        lblSignup.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblSignup.setForeground(new java.awt.Color(255, 255, 255));
        lblSignup.setText(" SIGN UP");

        javax.swing.GroupLayout btnSignupLayout = new javax.swing.GroupLayout(btnSignup);
        btnSignup.setLayout(btnSignupLayout);
        btnSignupLayout.setHorizontalGroup(
            btnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSignupLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnSignupLayout.setVerticalGroup(
            btnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSignupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSignup, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSignin.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 120, 40));

        getContentPane().add(panelSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 0, 460, 551));

        panelSignup.setBackground(new java.awt.Color(58, 111, 254));
        panelSignup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConfirm.setBackground(new java.awt.Color(58, 111, 254));
        lblConfirm.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblConfirm.setForeground(new java.awt.Color(204, 204, 204));
        lblConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_password_16px.png"))); // NOI18N
        lblConfirm.setText("Confirm Password");
        panelSignup.add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 140, 20));

        lblPassword_pw.setBackground(new java.awt.Color(58, 111, 254));
        lblPassword_pw.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblPassword_pw.setForeground(new java.awt.Color(204, 204, 204));
        lblPassword_pw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_password_16px.png"))); // NOI18N
        lblPassword_pw.setText("Password");
        panelSignup.add(lblPassword_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, 20));

        lblUser_su.setBackground(new java.awt.Color(58, 111, 254));
        lblUser_su.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblUser_su.setForeground(new java.awt.Color(204, 204, 204));
        lblUser_su.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_user_16px_1.png"))); // NOI18N
        lblUser_su.setText("User Name");
        panelSignup.add(lblUser_su, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 20));

        lblSignUp.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lblSignUp.setText("SignUp");
        panelSignup.add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 34, -1, -1));

        txtUser_su.setBackground(new java.awt.Color(58, 111, 254));
        txtUser_su.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtUser_su.setForeground(new java.awt.Color(255, 255, 255));
        txtUser_su.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtUser_su.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUser_suFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUser_suFocusLost(evt);
            }
        });
        panelSignup.add(txtUser_su, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 150, 346, 40));

        chkShowpassword_pw.setForeground(new java.awt.Color(255, 255, 255));
        chkShowpassword_pw.setText("Show Password");
        chkShowpassword_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowpassword_pwActionPerformed(evt);
            }
        });
        panelSignup.add(chkShowpassword_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 379, 120, -1));

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("I have Account");
        jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox2StateChanged(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        panelSignup.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 496, 130, -1));

        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Trainning department" }));
        cboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRoleActionPerformed(evt);
            }
        });
        panelSignup.add(cboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 378, 130, -1));

        txtPassWord_su.setBackground(new java.awt.Color(58, 111, 254));
        txtPassWord_su.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtPassWord_su.setForeground(new java.awt.Color(255, 255, 255));
        txtPassWord_su.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtPassWord_su.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassWord_suFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassWord_suFocusLost(evt);
            }
        });
        panelSignup.add(txtPassWord_su, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 227, 346, 40));

        txtConfirm_su.setBackground(new java.awt.Color(58, 111, 254));
        txtConfirm_su.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtConfirm_su.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirm_su.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtConfirm_su.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirm_suFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirm_suFocusLost(evt);
            }
        });
        panelSignup.add(txtConfirm_su, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 304, 346, 40));

        btnCreate.setBackground(new java.awt.Color(249, 126, 86));
        btnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateMouseExited(evt);
            }
        });

        lblLogin1.setBackground(new java.awt.Color(102, 102, 102));
        lblLogin1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblLogin1.setForeground(new java.awt.Color(0, 0, 0));
        lblLogin1.setText("CREATE");

        javax.swing.GroupLayout btnCreateLayout = new javax.swing.GroupLayout(btnCreate);
        btnCreate.setLayout(btnCreateLayout);
        btnCreateLayout.setHorizontalGroup(
            btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCreateLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        btnCreateLayout.setVerticalGroup(
            btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSignup.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lblExit1.setBackground(new java.awt.Color(255, 255, 255));
        lblExit1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(204, 204, 204));
        lblExit1.setText("X");
        lblExit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExit1MouseExited(evt);
            }
        });
        panelSignup.add(lblExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 40, 40));

        getContentPane().add(panelSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 460, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        // TODO add your handling code here:
        this.flag_user = true;
        up_down_text_field_user();
    }//GEN-LAST:event_txtUserMouseClicked

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        // TODO add your handling code here:
            this.flag_user = false;
            up_down_text_field_user();
//            up_down_textField(lblUser, txtUser, false);
        
    }//GEN-LAST:event_txtUserFocusLost

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
        this.flag_user = true;
        up_down_text_field_user();
//            up_down_textField(lblUser, txtUser, true);
        
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        this.flag_password = true;
        up_down_text_field_password();
          
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
        this.flag_password = false;
        up_down_text_field_password();
    }//GEN-LAST:event_txtPasswordFocusLost

    private void chkPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPasswordActionPerformed
        // TODO add your handling code here:
        if (chkPassword.isSelected()) {
            txtPassword.setEchoChar((char)0); //password = JPasswordField
        } else {
           txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkPasswordActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(251, 162, 114));
        lblLogin.setForeground(new Color(76, 74, 73));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(249,126,86));
        lblLogin.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseEntered
        // TODO add your handling code here:
        btnSignup.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(249,126,86)));
        lblSignup.setForeground(new Color(249,126,86));
    }//GEN-LAST:event_btnSignupMouseEntered

    private void btnSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseExited
        // TODO add your handling code here:
        btnSignup.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white));
        lblSignup.setForeground(Color.white);
    }//GEN-LAST:event_btnSignupMouseExited

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:    
        lblExit.setForeground(Color.red);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        // TODO add your handling code here:
        lblExit.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_lblExitMouseExited

    private void btnSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseClicked
        // TODO add your handling code here:
        panelSignin.setVisible(false);
        panelSignup.setVisible(true);
    }//GEN-LAST:event_btnSignupMouseClicked

    private void btnCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateMouseEntered

    private void btnCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateMouseExited

    private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jCheckBox2StateChanged

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        panelSignup.setVisible(false);
        panelSignin.setVisible(true);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
       Login();
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        // TODO add your handling code here:
        create();
            
    }//GEN-LAST:event_btnCreateMouseClicked

    private void cboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRoleActionPerformed

    private void txtUser_suFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser_suFocusGained
        // TODO add your handling code here:
        lblUser_su.setVisible(false);
    }//GEN-LAST:event_txtUser_suFocusGained

    private void txtUser_suFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser_suFocusLost
        // TODO add your handling code here:
        if(txtUser_su.getText().equals("")==false)
            lblUser_su.setVisible(false);
        else lblUser_su.setVisible(true);
    }//GEN-LAST:event_txtUser_suFocusLost

    private void txtPassWord_suFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassWord_suFocusGained
        // TODO add your handling code here:
        lblPassword_pw.setVisible(false);
        
    }//GEN-LAST:event_txtPassWord_suFocusGained

    private void txtPassWord_suFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassWord_suFocusLost
        // TODO add your handling code here:
        if(txtPassWord_su.getText().equalsIgnoreCase("")==false)
            lblPassword_pw.setVisible(false);
        else lblPassword_pw.setVisible(true);
    }//GEN-LAST:event_txtPassWord_suFocusLost

    private void txtConfirm_suFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirm_suFocusGained
        // TODO add your handling code here:
        lblConfirm.setVisible(false);
    }//GEN-LAST:event_txtConfirm_suFocusGained

    private void txtConfirm_suFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirm_suFocusLost
        // TODO add your handling code here:
        if(txtConfirm_su.getText().equals("")==false)
            lblConfirm.setVisible(false);
        else lblConfirm.setVisible(true);
    }//GEN-LAST:event_txtConfirm_suFocusLost

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblExit1MouseClicked

    private void lblExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseEntered
        // TODO add your handling code here:
         lblExit1.setForeground(Color.red);
    }//GEN-LAST:event_lblExit1MouseEntered

    private void lblExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseExited
        // TODO add your handling code here:
        lblExit1.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblExit1MouseExited

    private void chkShowpassword_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowpassword_pwActionPerformed
        // TODO add your handling code here:
        if (chkShowpassword_pw.isSelected()) {
            txtPassWord_su.setEchoChar((char)0); //password = JPasswordField
            txtConfirm_su.setEchoChar((char)0);
        } else {
           txtPassWord_su.setEchoChar('*');
           txtConfirm_su.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowpassword_pwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCreate;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JPanel btnSignup;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JCheckBox chkPassword;
    private javax.swing.JCheckBox chkShowpassword_pw;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblEduSys;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword_pw;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblSignup;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUser_su;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelImage;
    private javax.swing.JPanel panelSignin;
    private javax.swing.JPanel panelSignup;
    private javax.swing.JPasswordField txtConfirm_su;
    private javax.swing.JPasswordField txtPassWord_su;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUser_su;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent arg0) {
        
        
        
    }

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void repareLogin() {
        panelSignup.setVisible(false);
        lblUser.setOpaque(true);
        lblPassword.setOpaque(true);
        load_acc();
    }
    
    public void Login() {
        String user = txtUser.getText();
        String pass = txtPassword.getText();
        flag = false;
        for(Account i: ListAcc) {
            if(user.equals(i.getUser_name())&&pass.equals(i.getPassword())) {
                JOptionPane.showMessageDialog(this, "Logged in sucsessfully");
                new Main(i.getRole()).setVisible(true);
                flag = true;
                this.dispose();
                break;
                
            }
        }
        if(flag==false) {
            JOptionPane.showMessageDialog(this, "User name or password Incorrect!");
        }
    }

    private void create() {
        Error_manage();
        try {
            
            java.sql.Connection conn = DriverManager.getConnection(url, userName, password);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String sql = "INSERT INTO USERS VALUES (?,?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, txtUser_su.getText());
            st.setString(2, txtPassWord_su.getText());
            st.setInt(3, cboRole.getSelectedItem()=="Student"?0:1);
            st.executeUpdate();
            conn.close();
            st.close();
            JOptionPane.showMessageDialog(this, "Your account has been created");
            load_acc();
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void load_acc() {
        ListAcc.clear();
        try {
            java.sql.Connection conn = DriverManager.getConnection(url, userName, password);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Statement st = conn.createStatement();
            String sql = "SELECT * FROM USERS";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()) {
                Account acc = new Account(rs.getString(1), rs.getString(2), rs.getInt(3));
                ListAcc.add(acc);
            }
            System.out.println(ListAcc.size());
            rs.close();
            st.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    void up_down_textField(JLabel label,JTextField textField, Boolean flag) {
        // maxY là ở trạng thái bình thường
        int maxY = label.getY();
        int minY = label.getY()-25;
        if(textField.getText().equalsIgnoreCase("")==false&&label.getY()==maxY) {
            System.out.println("ok");
        } else {
            Timer timer = new Timer(10, this);
            timer.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent arg0) {
                    if(flag == false) {
                        if(label.getY()<=minY) {
                            timer.stop();
                        }
                        label.setLocation(label.getX()-5,label.getY()+5);
                        textField.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE));
                    }
                    if(flag == true) {
                        System.out.println(label.getY());
                        if(label.getY()==minY) 
                            timer.stop();
                        if(label.getY()>=maxY) {
                            label.setLocation(lblUser.getX()+5, lblUser.getY()-5);  
                            label.setBackground(new Color(58,111,254));
                            textField.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.WHITE));
                        }
                    }
                }
            });
            timer.start();
        }
    }
    
    void up_down_text_field_user() {
        // x = 70, y = 210
        if(txtUser.getText().equalsIgnoreCase("")==false&&lblUser.getY()==195) {
            System.out.println("ok");
        }
        else {
            Timer timer_user = new Timer(10,  this);
            timer_user.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent arg0) {
                    if(flag_user==false) {
                        if(lblUser.getY()>=210)
                            timer_user.stop();
                        lblUser.setLocation(lblUser.getX()-5, lblUser.getY()+5);
                        txtUser.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE));
                        System.out.println(lblUser.getLocation());   
                    }
                    if(flag_user==true) {
                        if(lblUser.getY()==195)
                            timer_user.stop();
                        if(lblUser.getY()>=200) {
                            lblUser.setLocation(lblUser.getX()+5, lblUser.getY()-5);  
                            lblUser.setBackground(new Color(58,111,254));
                            txtUser.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.WHITE));
                        }  
                    }
                }
            });
            timer_user.start();
        }

        
    }
    
    void up_down_text_field_password() {
        
        //x = 70, y = 340\
        if(txtPassword.getText().equalsIgnoreCase("")==false&&lblPassword.getY()<=325)
            System.out.println("ok");
        else {
            Timer timer_pw = new Timer(10, this);
            timer_pw.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent arg0) {
                    if(flag_password==false) {
                        if(lblPassword.getY()==340)
                            timer_pw.stop();
                        lblPassword.setLocation(lblPassword.getX()-5, lblPassword.getY()+5);
                        txtPassword.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE));

                    }
                    if(flag_password==true) {
                        if(lblPassword.getY()==325)
                           timer_pw.stop();
                        lblPassword.setLocation(lblPassword.getX()+5, lblPassword.getY()-5);
                        lblPassword.setBackground(new Color(58,111,254));
                        txtPassword.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.WHITE));
                    }


                    
                }
            });
            timer_pw.start();
        }
    }
    void Error_manage() {
        if(txtUser_su.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "User name invalid");
        }
        for(Account i : ListAcc) {
            if(i.getUser_name().equals(txtUser_su.getText())) {
                JOptionPane.showMessageDialog(this, "User name is already taken");
                return;
            } 
            
        }
        if(txtPassWord_su.getText().equalsIgnoreCase(txtConfirm_su.getText())==false) {
            JOptionPane.showMessageDialog(this, "2 Password is not match");
            return;
        }
        if(txtPassWord_su.getText().length()<=6) {
            JOptionPane.showMessageDialog(this, "Password must be more than 6 characters");
            return;
        }
    }
    
}
