/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j3_ps18851_phamvinhsang_asm.UI;

import j3_ps18851_phamvinhsang_asm.Enity.Grade;
import j3_ps18851_phamvinhsang_asm.Enity.Student;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Sang
 */
public class ScoreManage extends javax.swing.JFrame {

    /**
     * Creates new form StudentManage
     */
    int role;
    int index = 0;
    String user = "sa";
    String password = "songlong";
    String url = "jdbc:sqlserver://localhost:1433;Database=PS18851_PhamVinhSang_ASM_J3";
    boolean saveFlag = true;
    ArrayList<Grade> listScore = new ArrayList<>();
    ArrayList<Student> listSV = new ArrayList<>();
    public ScoreManage(int role) {
        setUndecorated(true);
        initComponents();
        loadDataToArr();
        loadDataToTable();
        
        loadDataStudentToArr();
        tblScore.setRowHeight(25);
        setEditContent(false);
        setEnableButton(false);
        this.role=role;
    }

    private ScoreManage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_group = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        panel3 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        btnDel = new java.awt.Panel();
        jLabel10 = new javax.swing.JLabel();
        btnAdd = new java.awt.Panel();
        jLabel12 = new javax.swing.JLabel();
        btnSave = new java.awt.Panel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIDSearch = new javax.swing.JTextField();
        btnSearch = new java.awt.Panel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblName_find = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPhysics = new javax.swing.JTextField();
        txtEnglish = new javax.swing.JTextField();
        txtInformatic = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblAverage = new javax.swing.JLabel();
        btnFirst1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblScore = new javax.swing.JTable();
        btnFirst = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        btnPrev = new javax.swing.JLabel();
        btnlast = new javax.swing.JLabel();

        panel3.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(98, 49, 219));
        jLabel1.setText("SCORE MANAGE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 360, 48));

        btnUpdate.setBackground(new java.awt.Color(98, 49, 219));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_renew_25px.png"))); // NOI18N
        jLabel9.setText("Update");

        javax.swing.GroupLayout btnUpdateLayout = new javax.swing.GroupLayout(btnUpdate);
        btnUpdate.setLayout(btnUpdateLayout);
        btnUpdateLayout.setHorizontalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(21, 21, 21))
        );
        btnUpdateLayout.setVerticalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 110, 40));

        btnDel.setBackground(new java.awt.Color(98, 49, 219));
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_delete_document_25px.png"))); // NOI18N
        jLabel10.setText("Delete");

        javax.swing.GroupLayout btnDelLayout = new javax.swing.GroupLayout(btnDel);
        btnDel.setLayout(btnDelLayout);
        btnDelLayout.setHorizontalGroup(
            btnDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnDelLayout.setVerticalGroup(
            btnDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 110, 40));

        btnAdd.setBackground(new java.awt.Color(98, 49, 219));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_new_copy_25px.png"))); // NOI18N
        jLabel12.setText("Add");

        javax.swing.GroupLayout btnAddLayout = new javax.swing.GroupLayout(btnAdd);
        btnAdd.setLayout(btnAddLayout);
        btnAddLayout.setHorizontalGroup(
            btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnAddLayout.setVerticalGroup(
            btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 110, 40));

        btnSave.setBackground(new java.awt.Color(98, 49, 219));
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_save_25px.png"))); // NOI18N
        jLabel14.setText("Save");

        javax.swing.GroupLayout btnSaveLayout = new javax.swing.GroupLayout(btnSave);
        btnSave.setLayout(btnSaveLayout);
        btnSaveLayout.setHorizontalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSaveLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnSaveLayout.setVerticalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 110, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("ID:");

        btnSearch.setBackground(new java.awt.Color(98, 49, 219));
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_search_client_30px.png"))); // NOI18N
        jLabel15.setText("Search");

        javax.swing.GroupLayout btnSearchLayout = new javax.swing.GroupLayout(btnSearch);
        btnSearch.setLayout(btnSearchLayout);
        btnSearchLayout.setHorizontalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnSearchLayout.setVerticalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jLabel3.setText("Name:");

        lblName_find.setText("Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblName_find, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblName_find, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 420, -1));

        jLabel4.setText("English");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 20));

        jLabel5.setText("Informatics");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel6.setText("Physics");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));
        jPanel1.add(txtPhysics, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 230, -1));
        jPanel1.add(txtEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 230, -1));
        jPanel1.add(txtInformatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 230, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Average", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblAverage.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblAverage.setText("0.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAverage, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 100, 110));

        btnFirst1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_close_window_50px_1.png"))); // NOI18N
        btnFirst1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFirst1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFirst1MouseClicked(evt);
            }
        });
        jPanel1.add(btnFirst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 580));

        tblScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "English", "Informatics", "Physics","Average"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    tblScore.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblScoreMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            tblScoreMouseEntered(evt);
        }
    });
    jScrollPane2.setViewportView(tblScore);

    btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_first_50px.png"))); // NOI18N
    btnFirst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnFirst.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnFirstMouseClicked(evt);
        }
    });

    btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_next_50px_1.png"))); // NOI18N
    btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnNextMouseClicked(evt);
        }
    });

    btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_previous_50px.png"))); // NOI18N
    btnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnPrevMouseClicked(evt);
        }
    });

    btnlast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_last_50px.png"))); // NOI18N
    btnlast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnlast.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnlastMouseClicked(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFirst)
            .addGap(61, 61, 61)
            .addComponent(btnPrev)
            .addGap(49, 49, 49)
            .addComponent(btnNext)
            .addGap(38, 38, 38)
            .addComponent(btnlast)
            .addGap(76, 76, 76))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnlast, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(36, 36, 36))
    );

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 520, 576));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        try {
            this.saveFlag = false;
            txtIDSearch.setEditable(false);
            setEditContent(true);
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void tblScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblScoreMouseClicked
        // TODO add your handling code here:
        display(tblScore.getSelectedRow());
        
    }//GEN-LAST:event_tblScoreMouseClicked

    private void btnDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseClicked
        // TODO add your handling code here:
        DeleteScore();
    }//GEN-LAST:event_btnDelMouseClicked

    private void btnFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstMouseClicked
        // TODO add your handling code here:
        tblScore.setRowSelectionInterval(0, 0);
        display(0);
    }//GEN-LAST:event_btnFirstMouseClicked

    private void btnlastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlastMouseClicked
        // TODO add your handling code here:
        tblScore.setRowSelectionInterval(listScore.size()-1, listScore.size()-1);
        display(listScore.size()-1);
    }//GEN-LAST:event_btnlastMouseClicked

    private void btnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseClicked
        // TODO add your handling code here:
        int i = tblScore.getSelectedRow();
        if(i==0) 
            i = listScore.size();
        
        tblScore.setRowSelectionInterval(i-1, i-1);
        display(i-1);
        
    }//GEN-LAST:event_btnPrevMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        int i = tblScore.getSelectedRow();
        if(i==listScore.size()-1)
            i = -1;
        tblScore.setRowSelectionInterval(i+1, i+1);
        display(i+1);
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        validateScore();
        txtIDSearch.setEditable(true);
        System.out.println(saveFlag);
        saveData(saveFlag);
        
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        String id = "";
        boolean b = false;
        for(Student i: listSV) {
            if(txtIDSearch.getText().equals(i.getId())) {
                id = i.getName();
                lblName_find.setText(i.getName());
                b = true;
            }
        }
        if(b==false) {
            JOptionPane.showMessageDialog(this, "Student " +id+ " does not exist:");
            setEnableButton(false);
            clearContent();
        } else {
            boolean check = false;
            for(Grade i: listScore) {
                if(txtIDSearch.getText().equals(i.getIDStudent())){
                    check = true;
                    txtEnglish.setText(i.getEnglish()+"");
                    txtInformatic.setText(i.getInformatic()+"");
                    txtPhysics.setText(i.getPhysics()+"");
                    lblAverage.setText(df.format(i.getAverage())+"");
                    setEnableButton(true);
                    btnAdd.setBackground(new Color(172, 224, 226));
                    btnAdd.setEnabled(false);
                    break;
                }
            }
            if(check == true) {
                for(int i=0;i<tblScore.getRowCount();i++) {
                    if(tblScore.getValueAt(i, 0).equals(txtIDSearch.getText())) {
                        tblScore.setRowSelectionInterval(i, i);
                    }
                }
            }
            if(check == false) {
                JOptionPane.showMessageDialog(this, "This student has no grades, please add grades");
                this.saveFlag = true;
                clearContent();
                setEnableButton(true);
                btnUpdate.setBackground(new Color(172, 224, 226));
                btnUpdate.setEnabled(false);
                btnDel.setBackground(new Color(172, 224, 226));
                btnDel.setEnabled(false);
            }
            
        }
        
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        this.saveFlag = true;
        clearContent();
        setEditContent(true);
    }//GEN-LAST:event_btnAddMouseClicked

    private void tblScoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblScoreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblScoreMouseEntered

    private void btnFirst1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirst1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Main(role).setVisible(true);
    }//GEN-LAST:event_btnFirst1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel btnAdd;
    private java.awt.Panel btnDel;
    private javax.swing.JLabel btnFirst;
    private javax.swing.JLabel btnFirst1;
    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel btnPrev;
    private java.awt.Panel btnSave;
    private java.awt.Panel btnSearch;
    private java.awt.Panel btnUpdate;
    private javax.swing.JLabel btnlast;
    private javax.swing.ButtonGroup gender_group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAverage;
    private javax.swing.JLabel lblName_find;
    private java.awt.Panel panel3;
    private javax.swing.JTable tblScore;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextField txtIDSearch;
    private javax.swing.JTextField txtInformatic;
    private javax.swing.JTextField txtPhysics;
    // End of variables declaration//GEN-END:variables

    
    DecimalFormat df = new DecimalFormat("#.##");
    private void loadDataToArr() {
        listScore.clear();
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement st = conn.createStatement();
            String sql = "SELECT GRADE.*, Name FROM GRADE JOIN STUDENTS ON GRADE.Idstudent = STUDENTS.IdStudent";
            ResultSet rs = st.executeQuery(sql);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            while(rs.next()) {
                Grade g= new Grade();
                g.setIDStudent(rs.getString("IdStudent"));
                g.setName(rs.getString("Name"));
                g.setEnglish(rs.getDouble("English"));
                g.setInformatic(rs.getDouble("Informatics"));
                g.setPhysics(rs.getDouble("Physical"));
                g.setAverage();
                listScore.add(g);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    public boolean catch_bug() {
        StringBuilder sb = new StringBuilder();
       
        
        if (sb.length()>0) {
            JOptionPane.showMessageDialog(this, sb.toString());
            return false;
        }
        return true;
    }
    
    
    
    private void display(int i) {
        setEnableButton(true);
        btnAdd.setBackground(new Color(172, 224, 226));
        btnAdd.setEnabled(false);
        txtIDSearch.setText(listScore.get(i).getIDStudent());
        txtEnglish.setText(listScore.get(i).getEnglish() + "");
        txtInformatic.setText(listScore.get(i).getInformatic()+ "");
        txtPhysics.setText(listScore.get(i).getPhysics()+"");
        lblAverage.setText(df.format(listScore.get(i).getAverage())+"");
        lblName_find.setText(listScore.get(i).getName());
   }
    
    private void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel)tblScore.getModel();
        model.setRowCount(0);
        for(Grade i: listScore){
            Object[] obj = {i.getIDStudent(), i.getName(), 
                i.getEnglish(), i.getInformatic(), i.getPhysics(), df.format(i.getAverage())};
            model.addRow(obj);
        }
    }
       
    
    private void clearContent() {
         txtEnglish.setText("");
         txtInformatic.setText("");
         txtPhysics.setText("");
         lblAverage.setText("");
    }
    private void setEditContent(boolean flag) {
        txtEnglish.setEditable(flag);
        txtInformatic.setEditable(flag);
        txtPhysics.setEditable(flag);
    }
    private void saveData(boolean flag) {
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            String sql = "";
            if(flag == true) {
                for(Grade i : listScore) {
                    if(txtIDSearch.getText().equalsIgnoreCase(i.getIDStudent())) {
                        JOptionPane.showMessageDialog(this, "ID Duplicate");
                        return;
                    }
                }
                sql = "INSERT INTO GRADE(IdStudent,English,Informatics,physical) VALUES (?,?,?,?)";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, txtIDSearch.getText());
                st.setDouble(2, Double.parseDouble(txtEnglish.getText()));
                st.setDouble(3, Double.parseDouble(txtInformatic.getText()));
                st.setDouble(4, Double.parseDouble(txtPhysics.getText()));
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Insert Successfully");
                loadDataToArr();
                loadDataToTable();
                
            } else  {
                sql = "UPDATE GRADE SET English = ?, Informatics = ?,Physical = ? WHERE IdStudent = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setDouble(1, Double.parseDouble(txtEnglish.getText()));
                st.setDouble(2, Double.parseDouble(txtInformatic.getText()));
                st.setDouble(3, Double.parseDouble(txtPhysics.getText()));
                st.setString(4, txtIDSearch.getText());
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Update Successfully");
                txtIDSearch.setEditable(true);
                loadDataToArr();
                loadDataToTable();
            }
            
        } catch (Exception ex) {  
            JOptionPane.showMessageDialog(this, "Input invalid !");
            ex.printStackTrace();
        }
    }

    private void DeleteScore() {
        int dialog = JOptionPane.YES_NO_OPTION;
        if(JOptionPane.showConfirmDialog(null, "Are you sure ?","WARNING",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            try {
                int i = tblScore.getSelectedRow();
                Connection conn = DriverManager.getConnection(url, user, password);
                String sql = "DELETE GRADE WHERE IDStudent = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, String.valueOf(tblScore.getValueAt(i, 0)));
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Delete Successfully");
                loadDataToArr();
                loadDataToTable();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "You must choose student to delete");
                ex.printStackTrace();
            }
        }else {
            System.out.println("cancel");
        }
    }
    private void loadDataStudentToArr() {
        try {
            listSV.clear();
            int i = 0;
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM STUDENTS";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()) {
                
                Student sv = new Student(rs.getString("IdStudent"), rs.getString("Name"), rs.getString("Email"), rs.getString("PhoneNumber"),
                      rs.getString("AddressStudent"), rs.getBoolean("Gender"), rs.getString("ImageStudent"));
                listSV.add(sv);
                Vector v = new Vector();
            }
            conn.close();
            
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }
    private void setEnableButton(boolean flag) {
        btnAdd.setEnabled(flag);
        btnDel.setEnabled(flag);
        btnUpdate.setEnabled(flag);
        btnSave.setEnabled(flag);
        if(flag == true) {
            btnAdd.setBackground(new Color(98,49,219));
            btnUpdate.setBackground(new Color(98,49,219));
            btnDel.setBackground(new Color(98,49,219));
            btnSave.setBackground(new Color(98,49,219));
        } else  {
            btnAdd.setBackground(new Color(172, 224, 226));
            btnUpdate.setBackground(new Color(172, 224, 226));
            btnDel.setBackground(new Color(172, 224, 226));
            btnSave.setBackground(new Color(172, 224, 226));
        }
            
    }
    private void validateScore() {
        if(Double.parseDouble(txtEnglish.getText())<0||Double.parseDouble(txtEnglish.getText())>10
         ||Double.parseDouble(txtInformatic.getText())<0||Double.parseDouble(txtInformatic.getText())>10
         ||Double.parseDouble(txtPhysics.getText())<0||Double.parseDouble(txtPhysics.getText())>10) {
            JOptionPane.showMessageDialog(this, "Score must be in 0 to 10");
            return;
        }
    }

    
}
