/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j3_ps18851_phamvinhsang_asm.UI;

import j3_ps18851_phamvinhsang_asm.Enity.Student;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Sang
 */
public class StudentManage extends javax.swing.JFrame {

    /**
     * Creates new form StudentManage
     */
    int role;
    int index = 0;
    String user = "sa";
    String password = "songlong";
    String url = "jdbc:sqlserver://localhost:1433;Database=PS18851_PhamVinhSang_ASM_J3";
    boolean saveFlag = true;
    String path = "MacDinh.jpg";
    ArrayList<Student> listSV = new ArrayList<>();
    public StudentManage(int role) {
        setUndecorated(true);
        initComponents();
        loadDataToArr();
        loadDataToTable();
        lblImage.setIcon(resizeImage("src\\Image_design\\MacDinh.jpg"));
        tblStudent.setRowHeight(25);
        this.role = role;
    }

    private StudentManage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_group = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        panel3 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        cboMale = new javax.swing.JRadioButton();
        cboFemale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnUpdate = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        btnNew = new java.awt.Panel();
        jLabel8 = new javax.swing.JLabel();
        btnDel = new java.awt.Panel();
        jLabel10 = new javax.swing.JLabel();
        btnNew1 = new java.awt.Panel();
        jLabel12 = new javax.swing.JLabel();
        btnSave1 = new java.awt.Panel();
        jLabel13 = new javax.swing.JLabel();
        btnFirst1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnFirst = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        btnPrev = new javax.swing.JLabel();
        btnlast = new javax.swing.JLabel();

        panel3.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(98, 49, 219));
        jLabel1.setText("STUDENT MANAGE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 360, 48));

        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 115, 41, -1));

        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 157, 41, -1));

        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 199, 41, -1));

        jLabel5.setText("Phone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 243, 41, -1));

        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 287, 50, -1));

        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 333, 60, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 111, 210, -1));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 153, 210, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 195, 210, -1));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 239, 210, -1));

        lblImage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        lblImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 115, 170, 150));

        gender_group.add(cboMale);
        cboMale.setText("Male");
        jPanel1.add(cboMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 70, -1));

        gender_group.add(cboFemale);
        cboFemale.setText("Female");
        jPanel1.add(cboFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 320, 100));

        btnUpdate.setBackground(new java.awt.Color(98, 49, 219));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_renew_25px.png"))); // NOI18N
        jLabel9.setText("Update");

        javax.swing.GroupLayout btnUpdateLayout = new javax.swing.GroupLayout(btnUpdate);
        btnUpdate.setLayout(btnUpdateLayout);
        btnUpdateLayout.setHorizontalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(21, 21, 21))
        );
        btnUpdateLayout.setVerticalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 110, 40));

        btnNew.setBackground(new java.awt.Color(98, 49, 219));
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_new_copy_25px.png"))); // NOI18N
        jLabel8.setText("Add");

        javax.swing.GroupLayout btnNewLayout = new javax.swing.GroupLayout(btnNew);
        btnNew.setLayout(btnNewLayout);
        btnNewLayout.setHorizontalGroup(
            btnNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNewLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnNewLayout.setVerticalGroup(
            btnNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 110, 40));

        btnDel.setBackground(new java.awt.Color(98, 49, 219));
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_delete_document_25px.png"))); // NOI18N
        jLabel10.setText("Delete");

        javax.swing.GroupLayout btnDelLayout = new javax.swing.GroupLayout(btnDel);
        btnDel.setLayout(btnDelLayout);
        btnDelLayout.setHorizontalGroup(
            btnDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnDelLayout.setVerticalGroup(
            btnDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 110, 40));

        btnNew1.setBackground(new java.awt.Color(98, 49, 219));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_new_copy_25px.png"))); // NOI18N
        jLabel12.setText("Add");

        javax.swing.GroupLayout btnNew1Layout = new javax.swing.GroupLayout(btnNew1);
        btnNew1.setLayout(btnNew1Layout);
        btnNew1Layout.setHorizontalGroup(
            btnNew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNew1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnNew1Layout.setVerticalGroup(
            btnNew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnNew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 110, 40));

        btnSave1.setBackground(new java.awt.Color(98, 49, 219));
        btnSave1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSave1MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_save_25px.png"))); // NOI18N
        jLabel13.setText("Save");

        javax.swing.GroupLayout btnSave1Layout = new javax.swing.GroupLayout(btnSave1);
        btnSave1.setLayout(btnSave1Layout);
        btnSave1Layout.setHorizontalGroup(
            btnSave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSave1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnSave1Layout.setVerticalGroup(
            btnSave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 110, 40));

        btnFirst1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_close_window_50px_1.png"))); // NOI18N
        btnFirst1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFirst1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFirst1MouseClicked(evt);
            }
        });
        jPanel1.add(btnFirst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 580));

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "PhoneNumber", "Address","Gender","Image"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblStudentMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(tblStudent);

    btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_first_50px.png"))); // NOI18N
    btnFirst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnFirst.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnFirstMouseClicked(evt);
        }
    });

    btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_next_50px_1.png"))); // NOI18N
    btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnNextMouseClicked(evt);
        }
    });

    btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_previous_50px.png"))); // NOI18N
    btnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnPrevMouseClicked(evt);
        }
    });

    btnlast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_design/icons8_last_50px.png"))); // NOI18N
    btnlast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnlast.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnlastMouseClicked(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFirst)
            .addGap(61, 61, 61)
            .addComponent(btnPrev)
            .addGap(49, 49, 49)
            .addComponent(btnNext)
            .addGap(38, 38, 38)
            .addComponent(btnlast)
            .addGap(76, 76, 76))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnlast, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(36, 36, 36))
    );

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 520, 576));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        // TODO add your handling code here:
        clearContent();
        setEditContent(true);
        this.saveFlag=true;
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        try {
            this.saveFlag = false;
            setEditContent(true);
            txtId.setEditable(false);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        // TODO add your handling code here:
        display(tblStudent.getSelectedRow());
        setEditContent(false);
    }//GEN-LAST:event_tblStudentMouseClicked

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        // TODO add your handling code here:
         try {
            JFileChooser f = new JFileChooser("src\\j3_ps18851_phamvinhsang_asm\\Data");
            f.setDialogTitle("Open file");
            f.showOpenDialog(null);
            String image = f.getSelectedFile().getName();
            this.path = image;
             System.out.println(path);
            lblImage.setIcon(ResizeImage("src\\j3_ps18851_phamvinhsang_asm\\Data\\"+path));
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this, "you must choose image");
        }
    }//GEN-LAST:event_lblImageMouseClicked

    private void btnDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseClicked
        // TODO add your handling code here:
        DeleteStudent();
    }//GEN-LAST:event_btnDelMouseClicked

    private void btnFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstMouseClicked
        // TODO add your handling code here:
        tblStudent.setRowSelectionInterval(0, 0);
        display(0);
    }//GEN-LAST:event_btnFirstMouseClicked

    private void btnlastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlastMouseClicked
        // TODO add your handling code here:
        tblStudent.setRowSelectionInterval(listSV.size()-1, listSV.size()-1);
        display(listSV.size()-1);
    }//GEN-LAST:event_btnlastMouseClicked

    private void btnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseClicked
        // TODO add your handling code here:
        int i = tblStudent.getSelectedRow();
        if(i==0) 
            i = listSV.size();
        
        tblStudent.setRowSelectionInterval(i-1, i-1);
        display(i-1);
        
    }//GEN-LAST:event_btnPrevMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        int i = tblStudent.getSelectedRow();
        if(i==listSV.size()-1)
            i = -1;
        tblStudent.setRowSelectionInterval(i+1, i+1);
        display(i+1);
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnSave1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSave1MouseClicked
        // TODO add your handling code here:
        saveData(this.saveFlag);
    }//GEN-LAST:event_btnSave1MouseClicked

    private void btnFirst1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirst1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Main(role).setVisible(true);
    }//GEN-LAST:event_btnFirst1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel btnDel;
    private javax.swing.JLabel btnFirst;
    private javax.swing.JLabel btnFirst1;
    private java.awt.Panel btnNew;
    private java.awt.Panel btnNew1;
    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel btnPrev;
    private java.awt.Panel btnSave1;
    private java.awt.Panel btnUpdate;
    private javax.swing.JLabel btnlast;
    private javax.swing.JRadioButton cboFemale;
    private javax.swing.JRadioButton cboMale;
    private javax.swing.ButtonGroup gender_group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImage;
    private java.awt.Panel panel3;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    private ImageIcon resizeImage(String path) {
        ImageIcon myImage = new ImageIcon(path);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;  
    }

    private void loadDataToArr() {
        try {
            listSV.clear();
            int i = 0;
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM STUDENTS";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()) {
                
                Student sv = new Student(rs.getString("IdStudent"), rs.getString("Name"), rs.getString("Email"), rs.getString("PhoneNumber"),
                      rs.getString("AddressStudent"), rs.getBoolean("Gender"), rs.getString("ImageStudent"));
                listSV.add(sv);
                Vector v = new Vector();
            }
            conn.close();
            
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }
    public boolean catch_bug() {
        StringBuilder sb = new StringBuilder();
       
        if (txtId.getText().equals("")) {
            sb.append("ID null");
        }
        
        if (txtName.getText().equals("")) {
            sb.append("\nName is null");
        }
        if (txtEmail.getText().equals("")) {
            sb.append("\nEmail is null");
        }else if (!(txtEmail.getText().matches("\\w+@\\w+(\\.\\w+){1,2}"))) {
            sb.append("\nEmail invalid");
        }
        if (txtPhone.getText().equals("")) {
            sb.append("\nPhone number is null");
        
        }
        if (!(cboMale.isSelected()) && !(cboFemale.isSelected())) {
            sb.append("\nChoose gender");
        }
        
        if (sb.length()>0) {
            JOptionPane.showMessageDialog(this, sb.toString());
            return false;
        }
        return true;
    }
    
    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon myImage = new ImageIcon(ImagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    private void display(int i) {
        txtId.setText(listSV.get(i).getId());
        txtName.setText(listSV.get(i).getName());
        txtEmail.setText(listSV.get(i).getEmail());
        txtPhone.setText(listSV.get(i).getPhone());
        txtAddress.setText(listSV.get(i).getAddress());
        if(listSV.get(i).getGender()==true) 
            cboMale.setSelected(true);
        else 
            cboFemale.setSelected(true);
        lblImage.setIcon(ResizeImage("src\\j3_ps18851_phamvinhsang_asm\\Data\\" + listSV.get(i).getImage()));
    }

    private void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel)tblStudent.getModel();
        model.setRowCount(0);
        for(Student i:listSV) {
             Object[] obj = {i.getId(),i.getName(),i.getEmail(),i.getPhone(),i.getAddress(),i.getGender()==true?"Male":"Female",i.getImage()};
             model.addRow(obj);
        }
       
    
    }
    private void clearContent() {
        txtId.setText("");
        txtName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        cboMale.setSelected(false);
        cboFemale.setSelected(false);
        lblImage.setIcon(resizeImage("src\\Image_design\\MacDinh.jpg"));
    }
    private void setEditContent(boolean flag) {
        txtId.setEditable(flag);
        txtName.setEditable(flag);
        txtEmail.setEditable(flag);
        txtPhone.setEditable(flag);
        txtAddress.setEditable(flag);
        cboMale.setEnabled(flag);
        cboFemale.setEnabled(flag);
    }
    private void saveData(boolean flag) {
        try {
            
            Connection conn = DriverManager.getConnection(url, user, password);
            String sql = "";
            if(flag == true) {
                for(int i=0;i<listSV.size();i++) {
                    if(listSV.get(i).getId().equals(txtId.getText())) {
                        JOptionPane.showMessageDialog(this, "ID is Duplicate");
                        return;
                    }
                }
                sql = "INSERT INTO STUDENTS VALUES (?,?,?,?,?,?,?)";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, txtId.getText());
                st.setString(2, txtName.getText());
                st.setString(3, txtEmail.getText());
                st.setString(4, txtPhone.getText());
                st.setBoolean(5,cboMale.isSelected()==true?true:false);
                st.setString(6, txtAddress.getText());
                st.setString(7, path);
                JOptionPane.showMessageDialog(this, "Add new Student Succsessfully !!");
                st.executeUpdate();
                loadDataToArr();
                loadDataToTable();
            } else {
                sql = "UPDATE STUDENTS SET Name = ?, Email = ?, PhoneNumber = ?,Gender=?, AddressStudent = ?, ImageStudent = ? "
                        + "WHERE IdStudent = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, txtName.getText());
                st.setString(2, txtEmail.getText());
                st.setString(3, txtPhone.getText());
                st.setBoolean(4,cboMale.isSelected()==true?true:false);
                st.setString(5, txtAddress.getText());
                st.setString(6, path);
                st.setString(7, txtId.getText());
                JOptionPane.showMessageDialog(this, "Student " + txtId.getText() +" has been update !!");
                st.executeUpdate();
                loadDataToArr();
                loadDataToTable();
            }
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void DeleteStudent() {
        try {
            int dialog = JOptionPane.YES_NO_OPTION;
            if(JOptionPane.showConfirmDialog(null, "Are you sure ?","WARNING",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                DeleteScore();
                Connection conn = DriverManager.getConnection(url, user, password);
                String sql = "DELETE STUDENTS WHERE IdStudent = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, txtId.getText());
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Student " + txtId.getText() +" has been deleted ");
                loadDataToArr();
                loadDataToTable();
                conn.close();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    private void DeleteScore() {
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            String sql = "DELETE GRADE WHERE IdStudent = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, txtId.getText());
            st.executeUpdate();
            loadDataToArr();
            loadDataToTable();
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    
}
